### ISSUE TITLE
Wrong icon path

### ISSUE THREAD

**Issue by stoecker** [praszuk/josm-fastdriveway-plugin#1]
Hello,

the META-File of this is wrong. It misses "images/" in the path of the plugin icon. Please fix ASAP, because I get warning mails because of this from our automatic scripts. :-)

**Comment by praszuk** [comment]
Can you confirm it's ok now?
https://github.com/praszuk/josm-fastdriveway-plugin/commit/a6ba78baeafd99775a937a86821fa520bcc8040f

**Comment by stoecker** [comment]
Looks good to me, but I can only confirm when it is released ;-)

**Comment by praszuk** [comment]
Ok. The icon appeared on the wiki site, so I suppose it's ok now.
https://josm.openstreetmap.de/wiki/Plugins
